-- MySQL Script generated by MySQL Workbench
-- Thu Oct  5 14:34:33 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `account_id` VARCHAR(8) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`account_id`, `email`),
  UNIQUE INDEX `student_Id_UNIQUE` (`account_id` ASC),
  UNIQUE INDEX `account_name_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Teams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Teams` (
  `account_id` VARCHAR(8) NOT NULL,
  `team_number` INT NOT NULL,
  PRIMARY KEY (`team_number`, `account_id`),
  UNIQUE INDEX `team_id_UNIQUE` (`team_number` ASC),
  INDEX `fk_Teams_Users_membership1_idx` (`account_id` ASC),
  UNIQUE INDEX `student_id_UNIQUE` (`account_id` ASC),
  CONSTRAINT `fk_Teams_Users_membership1`
    FOREIGN KEY (`account_id`)
    REFERENCES `mydb`.`Users_membership` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Users_membership`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users_membership` (
  `account_id` VARCHAR(8) NOT NULL,
  `team_number` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `cohort` DECIMAL(1) NOT NULL,
  `gpa` FLOAT NOT NULL,
  `major` VARCHAR(10) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `password_salt` VARCHAR(45) NOT NULL,
  `password_question` VARCHAR(45) NOT NULL,
  `password_answer` VARCHAR(45) NOT NULL,
  INDEX `fk_Users_membership_Users1_idx` (`account_id` ASC, `email` ASC),
  PRIMARY KEY (`account_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `account_id_UNIQUE` (`account_id` ASC),
  INDEX `fk_Users_membership_Teams1_idx` (`team_number` ASC),
  CONSTRAINT `fk_Users_membership_Users1`
    FOREIGN KEY (`account_id` , `email`)
    REFERENCES `mydb`.`Users` (`account_id` , `email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_membership_Teams1`
    FOREIGN KEY (`team_number`)
    REFERENCES `mydb`.`Teams` (`team_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Files`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Files` (
  `file_owner` VARCHAR(8) NOT NULL,
  `file_id` INT NOT NULL,
  PRIMARY KEY (`file_id`),
  UNIQUE INDEX `file_id_UNIQUE` (`file_id` ASC),
  INDEX `fk_Files_Users_membership1_idx` (`file_owner` ASC),
  CONSTRAINT `fk_Files_Users_membership1`
    FOREIGN KEY (`file_owner`)
    REFERENCES `mydb`.`Users_membership` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Users_Roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users_Roles` (
  `account_id` VARCHAR(8) NOT NULL,
  `role_id` VARCHAR(45) NOT NULL,
  INDEX `fk_Roles_Users_membership1_idx` (`account_id` ASC),
  PRIMARY KEY (`role_id`, `account_id`),
  CONSTRAINT `fk_Roles_Users_membership1`
    FOREIGN KEY (`account_id`)
    REFERENCES `mydb`.`Users_membership` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Roles` (
  `role_id` INT NOT NULL,
  `role_name` VARCHAR(45) NOT NULL,
  INDEX `fk_Roles_Users_Roles1_idx` (`role_id` ASC),
  PRIMARY KEY (`role_id`),
  UNIQUE INDEX `role_id_UNIQUE` (`role_id` ASC),
  CONSTRAINT `fk_Roles_Users_Roles1`
    FOREIGN KEY (`role_id`)
    REFERENCES `mydb`.`Users_Roles` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Projects` (
  `team_id` VARCHAR(45) NOT NULL,
  `project_owner` VARCHAR(8) NOT NULL,
  `project_id` INT NOT NULL,
  `project_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`project_id`),
  UNIQUE INDEX `project_id_UNIQUE` (`project_id` ASC),
  INDEX `fk_Projects_Teams1_idx` (`team_id` ASC),
  INDEX `fk_Projects_Users_membership1_idx` (`project_owner` ASC),
  CONSTRAINT `fk_Projects_Teams1`
    FOREIGN KEY (`team_id`)
    REFERENCES `mydb`.`Teams` (`team_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Projects_Users_membership1`
    FOREIGN KEY (`project_owner`)
    REFERENCES `mydb`.`Users_membership` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`File_Types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`File_Types` (
  `file_id` INT NOT NULL,
  `file_type` VARCHAR(45) NOT NULL,
  `file_name` VARCHAR(45) NOT NULL,
  INDEX `fk_File_Types_Files1_idx` (`file_id` ASC),
  UNIQUE INDEX `file_id_UNIQUE` (`file_id` ASC),
  PRIMARY KEY (`file_id`),
  CONSTRAINT `fk_File_Types_Files1`
    FOREIGN KEY (`file_id`)
    REFERENCES `mydb`.`Files` (`file_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reflection`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reflection` (
  `team_number` INT NOT NULL,
  `reflection_owner` VARCHAR(8) NOT NULL,
  `reflection_id` INT NOT NULL,
  `deadline` BINARY(1) NOT NULL,
  PRIMARY KEY (`reflection_id`),
  INDEX `fk_Reflection_Teams1_idx` (`team_number` ASC, `reflection_owner` ASC),
  UNIQUE INDEX `reflection_id_UNIQUE` (`reflection_id` ASC),
  CONSTRAINT `fk_Reflection_Teams1`
    FOREIGN KEY (`team_number` , `reflection_owner`)
    REFERENCES `mydb`.`Teams` (`team_number` , `account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Meeting Time`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Meeting Time` (
  `team_number` INT NOT NULL,
  `timeslot` VARCHAR(45) NOT NULL,
  INDEX `fk_Meeting Time_Teams1_idx` (`team_number` ASC),
  UNIQUE INDEX `Teams_team_number_UNIQUE` (`team_number` ASC),
  UNIQUE INDEX `timeslot_UNIQUE` (`timeslot` ASC),
  PRIMARY KEY (`timeslot`),
  CONSTRAINT `fk_Meeting Time_Teams1`
    FOREIGN KEY (`team_number`)
    REFERENCES `mydb`.`Teams` (`team_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
