# Generated by Django 2.0.2 on 2018-03-27 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_auto_20180228_1509'),
        ('assignment', '0003_assignment_document'),
    ]

    operations = [
    ]
