# Generated by Django 2.0.3 on 2018-03-27 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_assignment_document'),
        ('assignment', '0002_auto_20180228_1509'),
    ]

    operations = [
    ]
