# Generated by Django 2.0.5 on 2018-05-07 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0004_merge_20180327_1138'),
        ('assignment', '0004_auto_20180420_2245'),
    ]

    operations = [
    ]
